namespace Demo_Interface03.Demo03
{
    interface IDemo
    {
        string? Name { get; }
        void m();
    }

    interface IAnotherDemo : IDemo
    {
        void m();
        void n();
    }

    // IMPLICIT IMPLEMENTATION
    class Demo : IAnotherDemo
    {

        private string? _name;          // backing data-field
        public string? Name             // property
        {
            get { return _name; }       // GET accessor
            set { _name = value; }      // SET accessor
        }

        public void m()
        {
        }

        public void n()
        {
        }
    }

    // EXPLICIT IMPLEMENTATION
    class Another : IAnotherDemo
    {
        // Auto-Implemented Property (code is generated by the language compiler)
        public string? Name             // property
        {
            get;                // GET accessor
            set;                // SET accessor
        }
        // public string? Name { get; set; }

        void IAnotherDemo.m()
        {
        }

        void IAnotherDemo.n()
        {
        }

        void IDemo.m()
        {
        }
    }

    /*
    abstract class MyBase : IAnotherDemo
    {
        abstract void IDemo.m();             // compiler error! Implementation expected

        virtual void IAnotherDemo.m() { }    // compiler error! implementation expected

        public void n() { }
    }
    */

}
